// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC93vM3ai_BgsbdMBxFmNOI-op5OG6wUqo',
    appId: '1:704204355455:web:a80dd2663a52bbe7718c4a',
    messagingSenderId: '704204355455',
    projectId: 'pa-mobile-3ebc5',
    authDomain: 'pa-mobile-3ebc5.firebaseapp.com',
    storageBucket: 'pa-mobile-3ebc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl3B8Kuf4cHrz54IKFZxqdQnNQUsCpYRs',
    appId: '1:704204355455:android:54c746a05841374f718c4a',
    messagingSenderId: '704204355455',
    projectId: 'pa-mobile-3ebc5',
    storageBucket: 'pa-mobile-3ebc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8YzD7zojC_cglrQOT4i5JJEXBBMy7RdM',
    appId: '1:704204355455:ios:5dedb98f3095a2a5718c4a',
    messagingSenderId: '704204355455',
    projectId: 'pa-mobile-3ebc5',
    storageBucket: 'pa-mobile-3ebc5.appspot.com',
    iosBundleId: 'com.example.managment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8YzD7zojC_cglrQOT4i5JJEXBBMy7RdM',
    appId: '1:704204355455:ios:5dedb98f3095a2a5718c4a',
    messagingSenderId: '704204355455',
    projectId: 'pa-mobile-3ebc5',
    storageBucket: 'pa-mobile-3ebc5.appspot.com',
    iosBundleId: 'com.example.managment',
  );
}
